# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcourses',
            name='departmentID',
            field=models.ForeignKey(default=b'NONE', on_delete=django.db.models.deletion.CASCADE, to='base.TestDepartments'),
        ),
    ]
