# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160319_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcourses',
            name='departmentID',
        ),
    ]
