# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20160321_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('courses', models.ManyToManyField(to='base.TestCourses')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TestDepartments')),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TestDepartments')),
                ('reqCourses', models.ManyToManyField(to='base.TestCourses')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('neededCourses', models.ManyToManyField(related_name='neededCourses', to='base.TestCourses')),
                ('takenCourses', models.ManyToManyField(related_name='takenCourses', to='base.TestCourses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TestUsers',
        ),
        migrations.AddField(
            model_name='electives',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Majors'),
        ),
    ]
