# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160323_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('numCredits', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestDepartments',
            new_name='Departments',
        ),
        migrations.RemoveField(
            model_name='testcourses',
            name='department',
        ),
        migrations.RemoveField(
            model_name='testcourses',
            name='prereqs',
        ),
        migrations.AlterField(
            model_name='electives',
            name='courses',
            field=models.ManyToManyField(to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='majors',
            name='reqCourses',
            field=models.ManyToManyField(to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='neededCourses',
            field=models.ManyToManyField(related_name='neededCourses', to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='takenCourses',
            field=models.ManyToManyField(related_name='takenCourses', to='base.Courses'),
        ),
        migrations.DeleteModel(
            name='TestCourses',
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Departments'),
        ),
        migrations.AddField(
            model_name='courses',
            name='prereqs',
            field=models.ManyToManyField(related_name='_courses_prereqs_+', to='base.Courses'),
        ),
    ]
