# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testcourses_departmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcourses',
            name='departmentID',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='base.TestDepartments'),
            preserve_default=False,
        ),
    ]
