# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160323_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='acronym',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
