# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_courses_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='acronym',
            field=models.TextField(default=b'0'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default=b'0'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.TextField(default=b'0'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='numCredits',
            field=models.IntegerField(default=b'0', null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='number',
            field=models.TextField(default=b'0'),
        ),
        migrations.AddField(
            model_name='substitutes',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Courses'),
        ),
    ]
