# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160324_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='electives',
            name='department',
        ),
        migrations.RemoveField(
            model_name='majors',
            name='department',
        ),
        migrations.AddField(
            model_name='departments',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Colleges'),
        ),
        migrations.AddField(
            model_name='majors',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Colleges'),
        ),
    ]
