# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160325_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Majors'),
        ),
    ]
