# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_pos_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corequisite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corequisite_course', to='base.Departments')),
                ('courseFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corequisite_courseFor', to='base.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='base.Departments')),
                ('courseFor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_courseFor', to='base.Departments')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='courses',
            name='classificationNeeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='substitutes',
            name='courseFor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_courseFor', to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='electives',
            name='courses',
            field=models.ManyToManyField(null=True, to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='majors',
            name='reqCourses',
            field=models.ManyToManyField(null=True, to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='semesters',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='courses', to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='substitutes',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_course', to='base.Courses'),
        ),
    ]
