# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20160329_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electives',
            name='courses',
            field=models.ManyToManyField(to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='majors',
            name='reqCourses',
            field=models.ManyToManyField(to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='semesters',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='base.Courses'),
        ),
    ]
