# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160329_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='base.Courses'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='courseFor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_courseFor', to='base.Courses'),
        ),
    ]
