# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20160410_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='electives',
            name='creditNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
