# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_electives_creditnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='electives',
            name='overlapWith',
            field=models.ManyToManyField(related_name='_electives_overlapWith_+', to='base.Electives'),
        ),
    ]
