# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_electives_overlapwith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_password', models.TextField()),
                ('new_password_1', models.TextField()),
                ('new_password_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PosElective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creditsNeeded', models.IntegerField(blank=True, null=True)),
                ('elective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Electives')),
                ('takenCourses', models.ManyToManyField(related_name='elective_takenCourses', to='base.Courses')),
            ],
        ),
    ]
