# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_password_poselective'),
    ]

    operations = [
        migrations.AddField(
            model_name='poselective',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Pos'),
        ),
    ]
