# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20160427_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourYrPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FourYrPlanMajor', to='base.Majors')),
                ('semesters', models.ManyToManyField(related_name='FourYrPlanSemesters', to='base.Semesters')),
            ],
        ),
    ]
