# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_fouryrplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesters',
            name='electives',
            field=models.ManyToManyField(related_name='electives_in_semester', to='base.Electives'),
        ),
    ]
